services:
  - type: web
    name: mzizibet
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket --workers 1 --bind 0.0.0.0:$PORT --timeout 120 run:app
